version: "3"
services:
  homeassistant:
    image: homeassistant/home-assistant:0.111.4
    ports:
      - "8123:8123"
    container_name: homeassistant
    volumes:
      - ./homeassistant:/config
      - ./custom_components:/config/custom_components
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
