on: push
name: on push
jobs:
  onPush:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint
        uses: cclauss/GitHub-Action-for-Flake8@master
        with:
          args: flake8 . --count --show-source --statistics
